"""
config/risk_profiles.py
Defines all risk profiles. The active profile is loaded from .env
and passed through every layer of the agent.
"""

RISK_PROFILES = {
    "conservative": {
        "display_name": "Conservative",
        "max_drawdown_pct": 5.0,
        "max_position_pct": 8.0,
        "risk_per_trade_pct": 0.75,
        "capital_per_trade_pct": 2.0,
        "cash_buffer_pct": 30.0,
        "stop_loss_pct": 1.0,
        "take_profit_pct": 1.2,
        "max_trade_notional_eur": 1500,
        "min_conviction": 0.75,
        "min_signal_score": 0.50,
        "paper_overrides": {
            "min_signal_score": 0.16,
            "min_conviction": 0.42,
            "max_trades_per_day": 8,
            "min_hold_minutes": 10,
            "max_hold_minutes": 90,
        },
        "vix_ceiling": 20,
        "max_trades_per_day": 3,
        "min_hold_minutes": 30,
        "max_hold_minutes": 240,
        "allowed_instruments": ["SPY", "QQQ", "GLD", "TLT"],
        "allow_individual_stocks": False,
        "allow_leveraged_etfs": False,
        "allow_short_selling": False,
        "max_short_position_pct": 0.0,
        "min_short_signal_score": 0.60,
        "dominant_signal_veto_threshold": 0.65,
        "max_swing_hold_days": 2,
        "max_concurrent_swings": 1,
        "swing_conviction_threshold": 0.80,
        "learned_hold_min_conviction": 0.80,
        "learned_hold_min_signal_score": 0.35,
        "learned_hold_min_minutes": 120,
        "learned_hold_max_minutes": 240,
        "hold_extension_minutes": 15,
        "hold_extension_max_count": 2,
        "hold_extension_min_pnl_pct": 0.05,
        "hold_extension_min_signal_score": 0.20,
        "hold_extension_fade_score": 0.10,
        "time_exit_cooldown_minutes": 60,
        "signal_weights": {
            "order_book_imbalance": 0.14,
            "tape_aggression":      0.10,
            "rsi_divergence":       0.22,
            "news_sentiment":       0.16,
            "vwap_deviation":       0.11,
            "macd_crossover":       0.07,
            "relative_strength":    0.06,
            "bollinger_squeeze":    0.08,
            "put_call_ratio":       0.06,
        },
    },
    "cautious": {
        "display_name": "Cautious",
        "max_drawdown_pct": 8.0,
        "max_position_pct": 12.0,
        "risk_per_trade_pct": 0.90,
        "capital_per_trade_pct": 3.0,
        "cash_buffer_pct": 25.0,
        "stop_loss_pct": 1.5,
        "take_profit_pct": 1.6,
        "max_trade_notional_eur": 2500,
        "min_conviction": 0.70,
        "min_signal_score": 0.42,
        "paper_overrides": {
            "min_signal_score": 0.14,
            "min_conviction": 0.38,
            "max_trades_per_day": 12,
            "min_hold_minutes": 8,
            "max_hold_minutes": 60,
        },
        "vix_ceiling": 25,
        "max_trades_per_day": 5,
        "min_hold_minutes": 20,
        "max_hold_minutes": 180,
        "allowed_instruments": ["SPY", "QQQ", "GLD", "TLT", "IVV"],
        "allow_individual_stocks": False,
        "allow_leveraged_etfs": False,
        "allow_short_selling": False,
        "max_short_position_pct": 0.0,
        "min_short_signal_score": 0.50,
        "dominant_signal_veto_threshold": 0.72,
        "max_swing_hold_days": 3,
        "max_concurrent_swings": 1,
        "swing_conviction_threshold": 0.75,
        "learned_hold_min_conviction": 0.80,
        "learned_hold_min_signal_score": 0.35,
        "learned_hold_min_minutes": 120,
        "learned_hold_max_minutes": 240,
        "hold_extension_minutes": 20,
        "hold_extension_max_count": 2,
        "hold_extension_min_pnl_pct": 0.05,
        "hold_extension_min_signal_score": 0.20,
        "hold_extension_fade_score": 0.10,
        "time_exit_cooldown_minutes": 60,
        "signal_weights": {
            "order_book_imbalance": 0.15,
            "tape_aggression":      0.13,
            "rsi_divergence":       0.19,
            "news_sentiment":       0.15,
            "vwap_deviation":       0.10,
            "macd_crossover":       0.07,
            "relative_strength":    0.06,
            "bollinger_squeeze":    0.09,
            "put_call_ratio":       0.06,
        },
    },
    "moderate": {
        "display_name": "Moderate",
        "max_drawdown_pct": 10.0,
        "max_position_pct": 15.0,
        "risk_per_trade_pct": 1.0,
        "capital_per_trade_pct": 5.0,
        "cash_buffer_pct": 15.0,
        "stop_loss_pct": 2.0,
        "take_profit_pct": 2.2,
        "max_trade_notional_eur": 5000,
        "min_conviction": 0.60,
        "min_signal_score": 0.35,
        "paper_overrides": {
            "min_signal_score": 0.10,
            "min_conviction": 0.35,
            "max_trades_per_day": 30,
            "min_hold_minutes": 5,
            "max_hold_minutes": 30,
        },
        "vix_ceiling": 30,
        "max_trades_per_day": 8,
        "min_hold_minutes": 15,
        "max_hold_minutes": 90,
        "allowed_instruments": ["SPY", "QQQ", "GLD", "TLT", "AAPL", "TSLA"],
        "allow_individual_stocks": True,
        "allow_leveraged_etfs": False,
        "allow_short_selling": True,
        "max_short_position_pct": 8.0,
        "min_short_signal_score": 0.18,
        "bull_short_signal_score": 0.22,
        "dominant_signal_veto_threshold": 0.80,
        "max_swing_hold_days": 3,
        "max_concurrent_swings": 2,
        "swing_conviction_threshold": 0.70,
        "learned_hold_min_conviction": 0.80,
        "learned_hold_min_signal_score": 0.35,
        "learned_hold_min_minutes": 120,
        "learned_hold_max_minutes": 240,
        "hold_extension_minutes": 30,
        "hold_extension_max_count": 2,
        "hold_extension_min_pnl_pct": 0.05,
        "hold_extension_min_signal_score": 0.20,
        "hold_extension_fade_score": 0.10,
        "time_exit_cooldown_minutes": 60,
        "signal_weights": {
            "order_book_imbalance": 0.21,
            "tape_aggression":      0.17,
            "rsi_divergence":       0.11,
            "news_sentiment":       0.14,
            "vwap_deviation":       0.07,
            "macd_crossover":       0.08,
            "relative_strength":    0.07,
            "bollinger_squeeze":    0.10,
            "put_call_ratio":       0.05,
        },
    },
    "growth": {
        "display_name": "Growth",
        "max_drawdown_pct": 15.0,
        "max_position_pct": 20.0,
        "risk_per_trade_pct": 1.25,
        "capital_per_trade_pct": 8.0,
        "cash_buffer_pct": 10.0,
        "stop_loss_pct": 2.5,
        "take_profit_pct": 3.0,
        "max_trade_notional_eur": 8000,
        "min_conviction": 0.55,
        "min_signal_score": 0.30,
        "paper_overrides": {
            "min_signal_score": 0.08,
            "min_conviction": 0.32,
            "max_trades_per_day": 40,
            "min_hold_minutes": 5,
            "max_hold_minutes": 25,
        },
        "vix_ceiling": 35,
        "max_trades_per_day": 12,
        "min_hold_minutes": 10,
        "max_hold_minutes": 60,
        "allowed_instruments": ["SPY", "QQQ", "IWM", "GLD", "TLT", "XOP", "XLF", "NVDA", "TSLA", "IBIT", "SMH", "PLTR", "AVGO", "AMD", "META"],
        "allow_individual_stocks": True,
        "allow_leveraged_etfs": False,
        "allow_short_selling": True,
        "max_short_position_pct": 12.0,
        "min_short_signal_score": 0.15,
        "bull_short_signal_score": 0.19,
        "dominant_signal_veto_threshold": 0.85,
        "max_swing_hold_days": 5,
        "max_concurrent_swings": 2,
        "swing_conviction_threshold": 0.65,
        "learned_hold_min_conviction": 0.80,
        "learned_hold_min_signal_score": 0.35,
        "learned_hold_min_minutes": 120,
        "learned_hold_max_minutes": 240,
        "hold_extension_minutes": 30,
        "hold_extension_max_count": 3,
        "hold_extension_min_pnl_pct": 0.05,
        "hold_extension_min_signal_score": 0.18,
        "hold_extension_fade_score": 0.08,
        "time_exit_cooldown_minutes": 45,
        "signal_weights": {
            "order_book_imbalance": 0.21,
            "tape_aggression":      0.20,
            "rsi_divergence":       0.09,
            "news_sentiment":       0.13,
            "vwap_deviation":       0.07,
            "macd_crossover":       0.09,
            "relative_strength":    0.07,
            "bollinger_squeeze":    0.10,
            "put_call_ratio":       0.04,
        },
    },
    "ultra_aggressive": {
        "display_name": "Ultra-Aggressive",
        "max_drawdown_pct": 20.0,
        "max_position_pct": 30.0,
        "risk_per_trade_pct": 2.0,
        "capital_per_trade_pct": 15.0,
        "cash_buffer_pct": 3.0,
        "stop_loss_pct": 3.5,
        "take_profit_pct": 4.5,
        "max_trade_notional_eur": 15000,
        "min_conviction": 0.45,
        "min_signal_score": 0.20,
        "paper_overrides": {
            "min_signal_score": 0.05,
            "min_conviction": 0.28,
            "max_trades_per_day": 80,
            "min_hold_minutes": 2,
            "max_hold_minutes": 15,
        },
        "vix_ceiling": 22,           # strict VIX cap for leveraged ETF eligibility
        "max_trades_per_day": 30,
        "min_hold_minutes": 3,
        "max_hold_minutes": 30,
        "allowed_instruments": [
            "SPY", "QQQ", "IWM", "GLD", "TLT", "XOP", "XLF",
            "NVDA", "AMD", "TSLA", "META", "AMZN", "PLTR", "AVGO",
            "SMH", "IBIT", "COIN", "MSTR", "ARM",
        ],
        "allow_individual_stocks": True,
        "allow_leveraged_etfs": True,    # TQQQ/SOXL gated by A+ grade + VIX < 22
        "leveraged_etf_tickers": ["TQQQ", "SOXL", "NVDL"],
        "leveraged_etf_max_hold_minutes": 345,  # exit by 3:45 PM ET — never swing
        "leveraged_etf_vix_ceiling": 22,
        "allow_short_selling": True,
        "max_short_position_pct": 15.0,
        "min_short_signal_score": 0.10,
        "bull_short_signal_score": 0.14,
        "dominant_signal_veto_threshold": 0.92,
        "max_swing_hold_days": 7,
        "max_concurrent_swings": 3,
        "swing_conviction_threshold": 0.58,
        "learned_hold_min_conviction": 0.80,
        "learned_hold_min_signal_score": 0.35,
        "learned_hold_min_minutes": 60,
        "learned_hold_max_minutes": 180,
        "hold_extension_minutes": 15,
        "hold_extension_max_count": 4,
        "hold_extension_min_pnl_pct": 0.03,
        "hold_extension_min_signal_score": 0.14,
        "hold_extension_fade_score": 0.06,
        "time_exit_cooldown_minutes": 20,
        "signal_weights": {
            "order_book_imbalance": 0.24,
            "tape_aggression":      0.22,
            "rsi_divergence":       0.06,
            "news_sentiment":       0.10,
            "vwap_deviation":       0.06,
            "macd_crossover":       0.11,
            "relative_strength":    0.07,
            "bollinger_squeeze":    0.10,
            "put_call_ratio":       0.04,
        },
    },
    "aggressive": {
        "display_name": "Aggressive",
        "max_drawdown_pct": 20.0,
        "max_position_pct": 25.0,
        "risk_per_trade_pct": 1.5,
        "capital_per_trade_pct": 12.0,
        "cash_buffer_pct": 5.0,
        "stop_loss_pct": 3.0,
        "take_profit_pct": 3.8,
        "max_trade_notional_eur": 12000,
        "min_conviction": 0.50,
        "min_signal_score": 0.25,
        "paper_overrides": {
            "min_signal_score": 0.06,
            "min_conviction": 0.30,
            "max_trades_per_day": 60,
            "min_hold_minutes": 3,
            "max_hold_minutes": 20,
        },
        "vix_ceiling": 50,
        "max_trades_per_day": 20,
        "min_hold_minutes": 5,
        "max_hold_minutes": 45,
        "allowed_instruments": ["SPY", "QQQ", "GLD", "TLT", "AAPL", "TSLA", "NVDA", "META", "AMZN"],
        "allow_individual_stocks": True,
        "allow_leveraged_etfs": False,
        "allow_short_selling": True,
        "max_short_position_pct": 15.0,
        "min_short_signal_score": 0.12,
        "bull_short_signal_score": 0.16,
        "dominant_signal_veto_threshold": 0.90,
        "max_swing_hold_days": 7,
        "max_concurrent_swings": 3,
        "swing_conviction_threshold": 0.60,
        "learned_hold_min_conviction": 0.80,
        "learned_hold_min_signal_score": 0.35,
        "learned_hold_min_minutes": 120,
        "learned_hold_max_minutes": 240,
        "hold_extension_minutes": 30,
        "hold_extension_max_count": 3,
        "hold_extension_min_pnl_pct": 0.05,
        "hold_extension_min_signal_score": 0.16,
        "hold_extension_fade_score": 0.08,
        "time_exit_cooldown_minutes": 30,
        "signal_weights": {
            "order_book_imbalance": 0.23,
            "tape_aggression":      0.20,
            "rsi_divergence":       0.07,
            "news_sentiment":       0.11,
            "vwap_deviation":       0.07,
            "macd_crossover":       0.10,
            "relative_strength":    0.07,
            "bollinger_squeeze":    0.11,
            "put_call_ratio":       0.04,
        },
    },
}


def get_profile(name: str) -> dict:
    profile = RISK_PROFILES.get(name, RISK_PROFILES["moderate"]).copy()
    profile["_name"] = name
    return profile
